version: 2.1

orbs:
  coin-flip: denislemire/coin-flip@0.0.5

executors:
  my-executor:
    docker:
      - image: cimg/base:2023.03

jobs:
  build:
    executor: my-executor
    resource_class: small
    steps:
      - run: echo “hello world”
      - run: mkdir -p workspace
      - coin-flip/coinflip
workflows:
  build:
    jobs:
      - build
